#!/usr/bin/bash
# venvsync: A tool to synchronize a loaded Python virtual environment 
# with the local virtual environment managed by Mason for Neovim,
# because I cannot wrap my head around the configurations.
#
# Opinionated Queer License (https://oql.avris.it/) 
#
# Copyright (c) 2024 makichiis 

if [ -z $VIRTUAL_ENV ]; then
    echo "No virtual environment enabled."
    exit 1
fi

pylint_match=$(pip list | grep -F pylint)
if [ -z "$pylint_match" ]; then
    echo "pylint not installed. The latest version will be installed."
    pip install pylint
fi

MASON_VENV_LOCALDIR=~/.local/share/nvim/mason/packages/pylint/venv 

rm -rf $MASON_VENV_LOCALDIR/*
cp -r $VIRTUAL_ENV/* $MASON_VENV_LOCALDIR  

